# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06f518e60b46f94814968fb07a76f0d1abc8028d4daab186ad6113d6d5bc5655d93cc5a9192a7d86e668298747273c2875317af77e9168e2a52a080d9f197dbd

test:
  secret_key_base: 0441cc9513bda2f0cee404088da50cf0f720fdbc9c888d73309b41ab22409ff72b9516cc5a568ed9fb94d578b40130c66eb8f72c5151375bcf44a55bb4dc85ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
